import urllib.request
import json

def test_query(prompt, threshold=None):
    req_data = {'requirement': prompt}
    if threshold is not None:
        req_data['threshold'] = threshold
    req = urllib.request.Request(
        'http://localhost:8000/api/workflow/retrieve',
        data=json.dumps(req_data).encode('utf-8'),
        headers={'Content-Type': 'application/json'}
    )
    res = urllib.request.urlopen(req)
    data = json.loads(res.read().decode())
    print(f'Query: "{prompt}"')
    print(f'  Matched: {data.get("matched")}')
    print(f'  Scenario: {data.get("scenario")}')
    print(f'  Score: {data.get("similarity_score")} (Threshold: {data.get("threshold")})')
    print(f'  Action: {data.get("action")}')
    if data.get("workflow"):
        print(f'  Nodes count: {len(data["workflow"].get("nodes", []))}')
    print('-'*55)
    return data

if __name__ == '__main__':
    print('='*55)
    print('STEP 15 AUTOMATED VERIFICATION TESTS')
    print('='*55)

    print('\n[Test 1 — Strong Match: Doctor Appointment]')
    t1 = test_query('Book an appointment with a doctor.')
    assert t1['matched'] == True
    assert t1['scenario'] == 'Doctor Appointment Booking'

    print('\n[Test 2 — Strong Match: Order Tracking]')
    t2 = test_query('Where is my order?')
    assert t2['matched'] == True
    assert t2['scenario'] == 'Order Tracking'

    print('\n[Test 3 — Strong Match: Lead Qualification]')
    t3 = test_query('Qualify this new sales lead and collect their requirements.')
    assert t3['matched'] == True
    assert t3['scenario'] == 'Lead Qualification'

    print('\n[Test 4 — No Match: Unrelated Quantum Physics Requirement]')
    t4 = test_query('Build a quantum physics satellite orbit calculation engine.')
    assert t4['matched'] == False
    assert t4['action'] == 'Existing Workflow Generator'

    print('\n[Test 5 — Boundary Testing: Adjusting Threshold]')
    # Test with strict threshold 0.80 on moderate query
    t5a = test_query('Book an appointment with a doctor.', threshold=0.80)
    print(f'  Strict 0.80 threshold result: Matched={t5a["matched"]}')
    # Test with lenient threshold 0.10
    t5b = test_query('Doctor visit', threshold=0.10)
    assert t5b['matched'] == True

    print('\n[Test 6 & 7 — End-to-End Workflow Creation with Fallback Verification]')
    # Let's test POST /api/workflows with match query
    create_req_match = urllib.request.Request(
        'http://localhost:8000/api/workflows',
        data=json.dumps({
            'name': 'Doctor Booking Test',
            'vertical': 'Healthcare OPD',
            'description': 'I want to book an appointment with Dr. Raman for fever tomorrow evening',
            'nodes': []
        }).encode('utf-8'),
        headers={'Content-Type': 'application/json'}
    )
    res_m = urllib.request.urlopen(create_req_match)
    wf_m = json.loads(res_m.read().decode())
    print('Creation with Matching Requirement:')
    print(f'  Workflow ID: {wf_m.get("workflow_id")}')
    print(f'  Retrieval Metadata: {wf_m.get("retrieval_metadata")}')
    assert wf_m['retrieval_metadata']['matched'] == True
    assert wf_m['retrieval_metadata']['action'] == 'Reused existing workflow'

    # Let's test POST /api/workflows with unrelated query (FALLBACK to existing generator)
    create_req_fallback = urllib.request.Request(
        'http://localhost:8000/api/workflows',
        data=json.dumps({
            'name': 'Satellite Orbit Planner',
            'vertical': 'Aerospace Physics',
            'description': 'Compute orbital decay simulations and collision avoidance protocols',
            'nodes': []
        }).encode('utf-8'),
        headers={'Content-Type': 'application/json'}
    )
    res_f = urllib.request.urlopen(create_req_fallback)
    wf_f = json.loads(res_f.read().decode())
    print('\nCreation with Unrelated Requirement (Fallback triggered):')
    print(f'  Workflow ID: {wf_f.get("workflow_id")}')
    print(f'  Retrieval Metadata: {wf_f.get("retrieval_metadata")}')
    assert wf_f['retrieval_metadata']['matched'] == False
    assert wf_f['retrieval_metadata']['action'] == 'Existing Workflow Generator'
    # Nodes must be generated by fallback generator!
    assert len(wf_f['workflow']['nodes']) > 0

    print('\n' + '='*55)
    print('ALL AUTOMATED VERIFICATION TESTS PASSED SUCCESSFULLY!')
    print('='*55)
